### ISSUE TITLE
rake db:seed, password is too short

### ISSUE THREAD

**Issue by zymiboxpay** [rubytaiwan/jobs.ruby.tw#33]
After running rake db:seed, It shows that the password is too short, here is the error messages:

```
➜  jobs.ruby.tw git:(master) ✗ rake db:seed --trace
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Password is too short (minimum is 8 characters)
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/validations.rb:79:in `raise_record_invalid'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/validations.rb:43:in `save!'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in `block in save!'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in `save!'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/persistence.rb:51:in `create!'
/Users/zhu/Documents/learning/rails/projects/jobs.ruby.tw/db/seeds.rb:10:in `<top (required)>'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:547:in `load_seed'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/bin/rake:33:in `<main>'
Tasks: TOP => db:seed
```

so I edit the file db/seed.rb, change the password 'rubytw' to 'rubytaiwan' to solve the problem.

**Comment by JuanitoFatas** [comment]
Feel free to propose your workaround as a pull request, thanks!

**Comment by majidpal** [comment]
I am getting same error but in ruby bundled with portus docker image. Please let me konw where can I find db/seed.rb file
